"""
data.py — Indian forensic officers, cases and locations dataset
All names, locations and case types are India-specific.
"""

OFFICERS = [
    {
        "id": "OFF-001",
        "name": "Rajesh Kumar Sharma",
        "rank": "Inspector",
        "specialization": "Fingerprint Analysis",
        "skills": ["fingerprint", "latent print", "dactyloscopy"],
        "location": "Mumbai",
        "state": "Maharashtra",
        "experience_years": 12,
        "success_rate": 94.5,
        "caseload": 3,
        "max_caseload": 6,
        "active": True,
    },
    {
        "id": "OFF-002",
        "name": "Priya Venkataraman",
        "rank": "Sub-Inspector",
        "specialization": "Digital Forensics",
        "skills": ["digital evidence", "cyber crime", "mobile forensics", "data recovery"],
        "location": "Bangalore",
        "state": "Karnataka",
        "experience_years": 7,
        "success_rate": 91.2,
        "caseload": 2,
        "max_caseload": 6,
        "active": True,
    },
    {
        "id": "OFF-003",
        "name": "Arun Singh Chauhan",
        "rank": "Inspector",
        "specialization": "DNA Analysis",
        "skills": ["dna", "blood analysis", "biological evidence", "serology"],
        "location": "Delhi",
        "state": "Delhi",
        "experience_years": 15,
        "success_rate": 97.1,
        "caseload": 4,
        "max_caseload": 5,
        "active": True,
    },
    {
        "id": "OFF-004",
        "name": "Meenakshi Iyer",
        "rank": "Sub-Inspector",
        "specialization": "Facial Recognition",
        "skills": ["facial recognition", "cctv analysis", "image enhancement", "biometric"],
        "location": "Chennai",
        "state": "Tamil Nadu",
        "experience_years": 5,
        "success_rate": 88.4,
        "caseload": 2,
        "max_caseload": 6,
        "active": True,
    },
    {
        "id": "OFF-005",
        "name": "Suresh Babu Reddy",
        "rank": "Inspector",
        "specialization": "Multi-Modal Biometrics",
        "skills": ["biometric", "iris scan", "fingerprint", "facial recognition", "voice analysis"],
        "location": "Hyderabad",
        "state": "Telangana",
        "experience_years": 10,
        "success_rate": 93.8,
        "caseload": 3,
        "max_caseload": 5,
        "active": True,
    },
    {
        "id": "OFF-006",
        "name": "Anjali Deshmukh",
        "rank": "Assistant Inspector",
        "specialization": "Toxicology & Chemical Analysis",
        "skills": ["toxicology", "poison detection", "drug analysis", "chemical evidence"],
        "location": "Pune",
        "state": "Maharashtra",
        "experience_years": 8,
        "success_rate": 90.6,
        "caseload": 2,
        "max_caseload": 6,
        "active": True,
    },
    {
        "id": "OFF-007",
        "name": "Mohammed Khalid Ansari",
        "rank": "Inspector",
        "specialization": "Ballistics & Firearms",
        "skills": ["ballistics", "firearms", "gunshot residue", "trajectory analysis"],
        "location": "Lucknow",
        "state": "Uttar Pradesh",
        "experience_years": 14,
        "success_rate": 95.3,
        "caseload": 3,
        "max_caseload": 5,
        "active": True,
    },
    {
        "id": "OFF-008",
        "name": "Kavitha Nambiar",
        "rank": "Sub-Inspector",
        "specialization": "Document Forgery & Handwriting",
        "skills": ["document analysis", "handwriting", "forgery detection", "ink analysis"],
        "location": "Kochi",
        "state": "Kerala",
        "experience_years": 6,
        "success_rate": 86.9,
        "caseload": 1,
        "max_caseload": 6,
        "active": True,
    },
    {
        "id": "OFF-009",
        "name": "Vikram Joshi",
        "rank": "Inspector",
        "specialization": "Cyber Crime & Financial Fraud",
        "skills": ["cyber crime", "financial fraud", "digital evidence", "cryptocurrency", "phishing"],
        "location": "Ahmedabad",
        "state": "Gujarat",
        "experience_years": 9,
        "success_rate": 92.4,
        "caseload": 4,
        "max_caseload": 6,
        "active": True,
    },
    {
        "id": "OFF-010",
        "name": "Sunita Patel",
        "rank": "Sub-Inspector",
        "specialization": "Crime Scene Investigation",
        "skills": ["crime scene", "evidence collection", "photography", "bloodstain pattern"],
        "location": "Jaipur",
        "state": "Rajasthan",
        "experience_years": 4,
        "success_rate": 82.7,
        "caseload": 2,
        "max_caseload": 6,
        "active": True,
    },
    {
        "id": "OFF-011",
        "name": "Deepak Narayan Mishra",
        "rank": "Inspector",
        "specialization": "Narcotics & Drug Trafficking",
        "skills": ["narcotics", "drug trafficking", "chemical analysis", "undercover"],
        "location": "Patna",
        "state": "Bihar",
        "experience_years": 11,
        "success_rate": 89.1,
        "caseload": 3,
        "max_caseload": 5,
        "active": True,
    },
    {
        "id": "OFF-012",
        "name": "Lakshmi Subramanian",
        "rank": "Assistant Inspector",
        "specialization": "Digital Forensics",
        "skills": ["digital evidence", "social media", "email forensics", "network forensics"],
        "location": "Coimbatore",
        "state": "Tamil Nadu",
        "experience_years": 5,
        "success_rate": 87.3,
        "caseload": 1,
        "max_caseload": 6,
        "active": True,
    },
    {
        "id": "OFF-013",
        "name": "Ravi Shankar Gupta",
        "rank": "Inspector",
        "specialization": "Fraud & White Collar Crime",
        "skills": ["financial fraud", "accounting forensics", "document analysis", "corporate crime"],
        "location": "Kolkata",
        "state": "West Bengal",
        "experience_years": 13,
        "success_rate": 91.7,
        "caseload": 2,
        "max_caseload": 5,
        "active": True,
    },
    {
        "id": "OFF-014",
        "name": "Fatima Sheikh",
        "rank": "Sub-Inspector",
        "specialization": "Fingerprint Analysis",
        "skills": ["fingerprint", "latent print", "AFIS", "dactyloscopy"],
        "location": "Nagpur",
        "state": "Maharashtra",
        "experience_years": 6,
        "success_rate": 88.9,
        "caseload": 3,
        "max_caseload": 6,
        "active": True,
    },
    {
        "id": "OFF-015",
        "name": "Harpreet Singh Bedi",
        "rank": "Inspector",
        "specialization": "Cybercrime & Network Security",
        "skills": ["cyber crime", "network forensics", "hacking investigation", "dark web"],
        "location": "Chandigarh",
        "state": "Punjab",
        "experience_years": 10,
        "success_rate": 93.2,
        "caseload": 2,
        "max_caseload": 5,
        "active": True,
    },
]

PENDING_CASES = [
    {
        "id": "CASE-MH-2024-001",
        "title": "Andheri ATM Card Cloning Ring",
        "crime_type": "Cyber Crime",
        "evidence_types": ["digital evidence", "cctv analysis", "financial fraud"],
        "priority": "Critical",
        "complexity": "High",
        "location": "Mumbai",
        "state": "Maharashtra",
        "estimated_days": 18,
        "description": "Organized ATM card cloning operation affecting 200+ victims in Andheri West.",
    },
    {
        "id": "CASE-DL-2024-002",
        "title": "Saket Hit-and-Run with Forged Documents",
        "crime_type": "Document Forgery",
        "evidence_types": ["document analysis", "fingerprint", "cctv analysis"],
        "priority": "High",
        "complexity": "Medium",
        "location": "Delhi",
        "state": "Delhi",
        "estimated_days": 10,
        "description": "Vehicle involved in fatal hit-and-run had forged registration and insurance papers.",
    },
    {
        "id": "CASE-KA-2024-003",
        "title": "Whitefield IT Firm Data Breach",
        "crime_type": "Cyber Crime",
        "evidence_types": ["digital evidence", "network forensics", "email forensics"],
        "priority": "Critical",
        "complexity": "High",
        "location": "Bangalore",
        "state": "Karnataka",
        "estimated_days": 21,
        "description": "Major IT firm's employee database leaked on dark web. 50,000 records compromised.",
    },
    {
        "id": "CASE-TN-2024-004",
        "title": "Kilpauk Poisoning Case",
        "crime_type": "Homicide",
        "evidence_types": ["toxicology", "dna", "biological evidence"],
        "priority": "Critical",
        "complexity": "High",
        "location": "Chennai",
        "state": "Tamil Nadu",
        "estimated_days": 25,
        "description": "Suspected poisoning death of a family of three. Toxicology results pending.",
    },
    {
        "id": "CASE-TS-2024-005",
        "title": "Banjara Hills Jewellery Heist",
        "crime_type": "Robbery",
        "evidence_types": ["fingerprint", "cctv analysis", "ballistics"],
        "priority": "High",
        "complexity": "Medium",
        "location": "Hyderabad",
        "state": "Telangana",
        "estimated_days": 12,
        "description": "Armed robbery at premium jewellery showroom. Two suspects identified on CCTV.",
    },
    {
        "id": "CASE-UP-2024-006",
        "title": "Lucknow Illegal Arms Cache",
        "crime_type": "Arms Trafficking",
        "evidence_types": ["ballistics", "firearms", "narcotics"],
        "priority": "High",
        "complexity": "Medium",
        "location": "Lucknow",
        "state": "Uttar Pradesh",
        "estimated_days": 14,
        "description": "Illegal arms cache discovered in warehouse. Linked to organized crime network.",
    },
    {
        "id": "CASE-MH-2024-007",
        "title": "Dharavi Narcotics Syndicate",
        "crime_type": "Drug Trafficking",
        "evidence_types": ["narcotics", "chemical analysis", "fingerprint"],
        "priority": "Critical",
        "complexity": "High",
        "location": "Mumbai",
        "state": "Maharashtra",
        "estimated_days": 30,
        "description": "Large-scale narcotics distribution network operating out of Dharavi slum area.",
    },
    {
        "id": "CASE-GJ-2024-008",
        "title": "Ahmedabad Investment Fraud Scheme",
        "crime_type": "Financial Fraud",
        "evidence_types": ["financial fraud", "document analysis", "digital evidence"],
        "priority": "High",
        "complexity": "High",
        "location": "Ahmedabad",
        "state": "Gujarat",
        "estimated_days": 20,
        "description": "Ponzi scheme defrauding 1,200 investors of ₹45 crore via fake real estate company.",
    },
    {
        "id": "CASE-WB-2024-009",
        "title": "Park Street Sexual Assault",
        "crime_type": "Sexual Assault",
        "evidence_types": ["dna", "biological evidence", "cctv analysis"],
        "priority": "Critical",
        "complexity": "High",
        "location": "Kolkata",
        "state": "West Bengal",
        "estimated_days": 15,
        "description": "Assault case with DNA evidence collected. CCTV footage from 3 angles available.",
    },
    {
        "id": "CASE-RJ-2024-010",
        "title": "Jaipur Heritage Temple Idol Theft",
        "crime_type": "Theft",
        "evidence_types": ["fingerprint", "cctv analysis", "document analysis"],
        "priority": "Medium",
        "complexity": "Low",
        "location": "Jaipur",
        "state": "Rajasthan",
        "estimated_days": 7,
        "description": "Ancient idols stolen from protected heritage temple. Multiple fingerprints recovered.",
    },
]

# Indian city distance matrix (approximate km between major cities)
CITY_DISTANCES = {
    ("Mumbai", "Mumbai"): 0,
    ("Mumbai", "Pune"): 150,
    ("Mumbai", "Nagpur"): 830,
    ("Mumbai", "Delhi"): 1400,
    ("Mumbai", "Bangalore"): 980,
    ("Mumbai", "Chennai"): 1330,
    ("Mumbai", "Hyderabad"): 710,
    ("Mumbai", "Ahmedabad"): 530,
    ("Mumbai", "Jaipur"): 1150,
    ("Mumbai", "Lucknow"): 1250,
    ("Mumbai", "Kolkata"): 1980,
    ("Mumbai", "Chandigarh"): 1490,
    ("Mumbai", "Kochi"): 1200,
    ("Mumbai", "Coimbatore"): 1100,
    ("Mumbai", "Patna"): 1700,
    ("Delhi", "Delhi"): 0,
    ("Delhi", "Pune"): 1480,
    ("Delhi", "Nagpur"): 1090,
    ("Delhi", "Mumbai"): 1400,
    ("Delhi", "Bangalore"): 2200,
    ("Delhi", "Chennai"): 2200,
    ("Delhi", "Hyderabad"): 1570,
    ("Delhi", "Ahmedabad"): 940,
    ("Delhi", "Jaipur"): 270,
    ("Delhi", "Lucknow"): 550,
    ("Delhi", "Kolkata"): 1470,
    ("Delhi", "Chandigarh"): 250,
    ("Delhi", "Kochi"): 2900,
    ("Delhi", "Coimbatore"): 2350,
    ("Delhi", "Patna"): 1000,
    ("Bangalore", "Bangalore"): 0,
    ("Bangalore", "Chennai"): 350,
    ("Bangalore", "Hyderabad"): 570,
    ("Bangalore", "Coimbatore"): 360,
    ("Bangalore", "Kochi"): 560,
    ("Bangalore", "Mumbai"): 980,
    ("Bangalore", "Pune"): 840,
    ("Bangalore", "Kolkata"): 1870,
    ("Bangalore", "Delhi"): 2200,
    ("Bangalore", "Chandigarh"): 2450,
    ("Chennai", "Chennai"): 0,
    ("Chennai", "Hyderabad"): 620,
    ("Chennai", "Coimbatore"): 500,
    ("Chennai", "Kochi"): 680,
    ("Chennai", "Bangalore"): 350,
    ("Chennai", "Mumbai"): 1330,
    ("Chennai", "Kolkata"): 1670,
    ("Hyderabad", "Hyderabad"): 0,
    ("Hyderabad", "Pune"): 560,
    ("Hyderabad", "Mumbai"): 710,
    ("Hyderabad", "Bangalore"): 570,
    ("Hyderabad", "Chennai"): 620,
    ("Hyderabad", "Delhi"): 1570,
    ("Hyderabad", "Kolkata"): 1510,
    ("Ahmedabad", "Ahmedabad"): 0,
    ("Ahmedabad", "Mumbai"): 530,
    ("Ahmedabad", "Pune"): 660,
    ("Ahmedabad", "Delhi"): 940,
    ("Ahmedabad", "Jaipur"): 670,
    ("Jaipur", "Jaipur"): 0,
    ("Jaipur", "Delhi"): 270,
    ("Jaipur", "Lucknow"): 570,
    ("Lucknow", "Lucknow"): 0,
    ("Lucknow", "Patna"): 490,
    ("Lucknow", "Delhi"): 550,
    ("Kolkata", "Kolkata"): 0,
    ("Kolkata", "Patna"): 590,
    ("Chandigarh", "Chandigarh"): 0,
    ("Chandigarh", "Delhi"): 250,
    ("Kochi", "Kochi"): 0,
    ("Kochi", "Coimbatore"): 190,
    ("Coimbatore", "Coimbatore"): 0,
    ("Patna", "Patna"): 0,
    ("Nagpur", "Nagpur"): 0,
    ("Nagpur", "Mumbai"): 830,
    ("Nagpur", "Hyderabad"): 500,
}

def get_distance(city1: str, city2: str) -> float:
    """Get distance between two Indian cities (in km)."""
    key = (city1, city2)
    rev_key = (city2, city1)
    if key in CITY_DISTANCES:
        return float(CITY_DISTANCES[key])
    if rev_key in CITY_DISTANCES:
        return float(CITY_DISTANCES[rev_key])
    return 1500.0  # default large distance for unknown pairs

def specialization_match_score(officer_skills: list, evidence_types: list) -> float:
    """Calculate how well officer skills match case evidence types."""
    if not officer_skills or not evidence_types:
        return 30.0
    matches = 0
    for skill in officer_skills:
        for evidence in evidence_types:
            if skill.lower() in evidence.lower() or evidence.lower() in skill.lower():
                matches += 1
    max_possible = max(len(officer_skills), len(evidence_types))
    return min(100.0, (matches / max_possible) * 100.0) if max_possible > 0 else 30.0
